on: push
jobs:
  create_file:
    runs-on: ubuntu-latest
    if: ${{ !(github.repository == 'Goldmensch/jtemplate' && github.ref_name == 'master')}}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          rm -f repo_metadata
          touch repo_metadata
          echo "REPO_OWNER=${{ github.repository_owner }}" >> repo_metadata
          echo "REPO_URL=github.com/${{ github.repository }}" >> repo_metadata
          echo "REPO_NAME=${{ github.repository }}" >> repo_metadata
        
          git add repo_metadata
          git commit --allow-empty -m "Add metadata file"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}